# Generated by Django 3.0.3 on 2022-03-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
